// packages/astro-typesafe-routes/src/components/link/react/react-link.tsx
import type { ComponentProps } from "react";
import { $path, type RouteOptions } from "../../../path.js";

export type ReactLinkProps = Omit<ComponentProps<"a">, "href"> & RouteOptions<any>;

export default function Link(props: ReactLinkProps) {
  const { children, to, params, search, searchParams, hash, trailingSlash, ...anchorProps } = props;

  const href = $path({ to, params, search, searchParams, hash, trailingSlash });

  return (
    <a href={href} {...anchorProps}>
      {children}
    </a>
  );
}

// packages/astro-typesafe-routes/src/components/link/vue/vue-link.vue
<template>
  <a :href="href" v-bind="$attrs">
    <slot></slot>
  </a>
</template>

<script setup lang="ts">
import { AnchorHTMLAttributes, computed, defineProps } from 'vue';
import { $path, RouteOptions } from '../../../path.js';

const props = defineProps<AnchorHTMLAttributes & RouteOptions>()

// Compute the href based on the provided props
const href = computed(() => {
  return $path({
    to: props.to,
    params: props.params,
    search: props.search,
    searchParams: props.searchParams,
    hash: props.hash,
    trailingSlash: props.trailingSlash,
  });
});
</script>
